server:
  port: 8087 
dbport: '27017'
dbname: bootDB
spring:
  application:
    name:  bootcointransaction-service
  cloud:
    config:
      uri: localhost:8888
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
